#pragma once
#include "pch.h"
#include"Mail.h"
#include"Post_Office.h"
#include"Person.h"
#include"Worker.h"
#include"Cashier.h"
#include"Client.h"
#include"Deliverer.h"
#include"Letter.h"
#include"Parcel.h"
#include"Distance_between_post_office.h"
